name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug
          mkdir -p output/debug
          find . -name "*.apk" -exec cp {} output/debug/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: output/
